version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install jest --global
      - ./api/tests/createCognitoUser.sh testuser
  build:
    commands:
      - npm run pretest
      - npm run test:api
      - npm run test:ci
      - npm run test:integration

reports:
  jest_reports:
    files:
      - "junit.xml"
    file-format: JUNITXML
