version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - ./api/tests/createCognitoUser.sh testuser
  build:
    commands:
      - npm test api -- --watchAll=false
      - npm test -- --watchAll=false

reports:
  jest_reports:
    files:
      - "testReports/*.xml"
    file-format: JUNITXML
