version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - ./api/tests/createCognitoUser.sh testuser
  build:
    commands:
      - jest api/tests/ --runInBand
      - npm run test:ci

reports:
  jest_reports:
    files:
      - "junit.xml"
    file-format: JUNITXML
