version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install jest --global
      - ./api/tests/createCognitoUser.sh testuser
  build:
    commands:
      - env
      - npm run test:prettest
      - npm run test:api
      - npm run test:ci
      - ./deployFrontend.sh

reports:
  jest_reports:
    files:
      - "junit.xml"
    file-format: JUNITXML
