---
Description: Set up Cognito pool

Parameters:
  NamePrefix:
    Type: String
    Description: prefix for naming all components
    MinLength: 3
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
  UserPoolId:
    Type: String
    MinLength: 3
  ServiceRoleArn:
    Type: String
    MinLength: 3
  QuestionnaireTableName:
    Type: String
    MinLength: 3
  QuestionTableName:
    Type: String
    MinLength: 3
  FeedbackTableName:
    Type: String
    MinLength: 3

Resources:
  AppSyncApi:
    Type: "AWS::AppSync::GraphQLApi"
    Description: "The GraphQL API for the Questionnaires App"
    Properties:
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      AdditionalAuthenticationProviders:
        - AuthenticationType: API_KEY
      Name: !Sub ${NamePrefix}
      UserPoolConfig:
        UserPoolId: !Ref UserPoolId
        AwsRegion: !Sub ${AWS::Region}
        DefaultAction: "ALLOW"
  ApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Description: "API access for non cognito authenticated users"
      Expires: 1644847457
  AppSyncSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Definition: |
        type Questionnaire @aws_api_key @aws_cognito_user_pools {
          id: ID!
          name: String
          questions: QuestionConnection
        }
        type QuestionConnection @aws_api_key @aws_cognito_user_pools {
          items: [Question]
        }
        type FeedbackConnection {
          items: [Feedback]
        }
        type Questionnaires {
          questionnaires: [Questionnaire!]!
        }
        type Feedback @aws_api_key @aws_cognito_user_pools{
          id: ID!
          questionId: ID!
          feedback: String
        }
        type Question @aws_api_key @aws_cognito_user_pools {
          id: ID!
          questionnaireId: ID!
          question: String
          feedback: FeedbackConnection
        }
        type Questions {
          questions: [Question!]!
        }
        type Query {
          getQuestions: Questions!
          getQuestion(id: ID!): Question
          getFeedback(id: ID!): Feedback
          getQuestionnaires: Questionnaires!
          getQuestionnaire(id: ID!): Questionnaire
          getQuestionnairePublic(id: ID!): Questionnaire @aws_api_key @aws_cognito_user_pools
        }
        type Mutation {
          saveQuestion(questionnaireId: ID!, question: String!): Question
          saveFeedback(questionId: ID!, feedback: String!): Feedback @aws_api_key @aws_cognito_user_pools
          saveQuestionnaire(name: String!): Questionnaire
          deleteQuestion(id: ID!): Question
          deleteQuestionnaire(id: ID!): Questionnaire
        }
        type Schema {
          query: Query
          mutation: Mutation
        }
  AppSyncQuestionnairesTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: !Sub ${NamePrefix}_questionnaires
      Description: "The Questionnaires Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref QuestionnaireTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncQuestionsTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: !Sub ${NamePrefix}_questions
      Description: "The Questions Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref QuestionTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncFeedbackTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: !Sub ${NamePrefix}_feedback
      Description: "The Feedback Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref FeedbackTableName
        AwsRegion: !Sub ${AWS::Region}

  AppSyncAllQuestionnairesQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getQuestionnaires
      DataSourceName: !GetAtt AppSyncQuestionnairesTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation" : "Query",
          "index" : "UserId-index",
          "query" : {
             "expression": "UserId = :userid",
             "expressionValues" : {
                ":userid" : $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
              }
           }
        }
      ResponseMappingTemplate: |
        {
          "questionnaires": $util.toJson($ctx.result.items)
        }
  AppSyncGetQuestionnaireQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getQuestionnaire
      DataSourceName: !GetAtt AppSyncQuestionnairesTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id),
            "UserId": $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncGetQuestionnairePublicQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getQuestionnairePublic
      DataSourceName: !GetAtt AppSyncQuestionnairesTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation" : "Query",
          "index" : "id-index",
          "query" : {
             "expression": "id = :id",
             "expressionValues" : {
                ":id" : $util.dynamodb.toDynamoDBJson($ctx.args.id)
              }
           }
        }
      ResponseMappingTemplate: "
        #if( $ctx.result.items.isEmpty() )
	        $util.toJson(null)
        #else
          $util.toJson($ctx.result.items[0])
        #end"

  AppSyncSaveQuestionnaireMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: saveQuestionnaire
      DataSourceName: !GetAtt AppSyncQuestionnairesTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($util.autoId()),
            "UserId": $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
          },
          "attributeValues": {
            "name": $util.dynamodb.toDynamoDBJson($ctx.args.name)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncDeleteQuestionnaireMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteQuestionnaire
      DataSourceName: !GetAtt AppSyncQuestionnairesTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "DeleteItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id),
            "UserId": $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncGetQuestionsQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getQuestions
      DataSourceName: !GetAtt AppSyncQuestionsTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation" : "Query",
          "index" : "UserId-index",
          "query" : {
             "expression": "UserId = :userid",
             "expressionValues" : {
                ":userid" : $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
              }
           }
        }
      ResponseMappingTemplate: |
        {
          "questions": $util.toJson($ctx.result.items)
        }

  AppSyncQuestionConnectionQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Questionnaire
      FieldName: questions
      DataSourceName: !GetAtt AppSyncQuestionsTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Query",
          "index": "QuestionnaireIdGSI",
          "query": {
              "expression": "questionnaireId = :questionnaireId",
              "expressionValues": {
                  ":questionnaireId": {
                      "S": "$context.source.id"
                  }
              }
           }
        }
      ResponseMappingTemplate: |
        {
          "items": $util.toJson($context.result.items)
        }

  AppSyncFeedbackConnectionQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Question
      FieldName: feedback
      DataSourceName: !GetAtt AppSyncFeedbackTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Query",
          "index": "QuestionIdGSI",
          "query": {
              "expression": "questionId = :questionId",
              "expressionValues": {
                  ":questionId": {
                      "S": "$context.source.id"
                  }
              }
           }
        }
      ResponseMappingTemplate: |
        {
          "items": $util.toJson($context.result.items)
        }

  AppSyncSaveQuestionMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: saveQuestion
      DataSourceName: !GetAtt AppSyncQuestionsTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($util.autoId()),
            "UserId": $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
          },
          "attributeValues": {
            "questionnaireId": $util.dynamodb.toDynamoDBJson($ctx.args.questionnaireId),
            "question": $util.dynamodb.toDynamoDBJson($ctx.args.question)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncSaveFeedbackMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: saveFeedback
      DataSourceName: !GetAtt AppSyncFeedbackTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($util.autoId())
          },
          "attributeValues": {
            "questionId": $util.dynamodb.toDynamoDBJson($ctx.args.questionId),
            "feedback": $util.dynamodb.toDynamoDBJson($ctx.args.feedback)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncGetQuestionQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getQuestion
      DataSourceName: !GetAtt AppSyncQuestionsTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id),
            "UserId": $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncGetFeedbackQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getFeedback
      DataSourceName: !GetAtt AppSyncFeedbackTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
          "consistentRead" : true
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncDeleteQuestionMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: deleteQuestion
      DataSourceName: !GetAtt AppSyncQuestionsTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "DeleteItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id),
            "UserId": $util.dynamodb.toDynamoDBJson($ctx.identity.sub)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

Outputs:
  GraphQLApiEndpoint:
    Description: The URL to the GraphQL Endpoint
    Value: !GetAtt AppSyncApi.GraphQLUrl
  GraphQLApiId:
    Description: The API ID of the GraphQL API
    Value: !GetAtt AppSyncApi.ApiId
  ApiKey:
    Description: The API KEY for public access to the GraphQL API
    Value: !GetAtt ApiKey.ApiKey
  
