version: 0.2

phases:
  build:
    commands:
      - CLOUDFORMATION_SRC_DIR="$CODEBUILD_SRC_DIR/api/infra"
      - aws cloudformation package --template-file "$CLOUDFORMATION_SRC_DIR/backend.yml" --s3-bucket "$DEPLOYMENT_BUCKET" --s3-prefix "packagedCloudformationAssets/$CODEBUILD_BUILD_ID" --output-template-file "$CLOUDFORMATION_SRC_DIR/packagedBackendTemplate.yml"
      - aws cloudformation package --template-file "$CLOUDFORMATION_SRC_DIR/frontend.yml" --s3-bucket "$DEPLOYMENT_BUCKET" --s3-prefix "packagedCloudformationAssets/$CODEBUILD_BUILD_ID" --output-template-file "$CLOUDFORMATION_SRC_DIR/packagedFrontendTemplate.yml"

artifacts:
  base-directory: $CLOUDFORMATION_SRC_DIR
  files:
    - "**/*"
