---
Description: Questionnaires API

Parameters:
  SiteURL:
    Type: String
    Description: URL of the website
    Default: http://localhost:3000

  ProjectName:
    Type: String
    Description: Name of the project - used to generate unique names for resources
    MinLength: 3
    AllowedPattern: "^[a-z][a-z0-9_-]*$"

  Environment:
    Type: String
    Description: Environment we are deploying in
    MinLength: 3
    AllowedPattern: "^[a-z][a-z0-9_-]*$"

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  CognitoPool:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "./cognito.yml"
      Parameters:
        SiteURL:
          Ref: SiteURL
        NamePrefix: !Sub ${ProjectName}-${Environment}
  DynamoDbTable:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "./dynamoDB.yml"
      Parameters:
        NamePrefix: !Sub ${ProjectName}-${Environment}
  AppsyncAPI:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "./appsyncAPI.yml"
      Parameters:
        NamePrefix: !Sub ${ProjectName}-${Environment}
        UserPoolId:
          Fn::GetAtt:
            - CognitoPool
            - Outputs.UserPoolId
        QuestionnaireTableName:
          Fn::GetAtt:
            - DynamoDbTable
            - Outputs.QuestionnaireTableID
        QuestionTableName:
          Fn::GetAtt:
            - DynamoDbTable
            - Outputs.QuestionTableID
        FeedbackTableName:
          Fn::GetAtt:
            - DynamoDbTable
            - Outputs.FeedbackTableID
        ServiceRoleArn:
          Fn::GetAtt:
            - DynamoDbTable
            - Outputs.DBRoleARN
  Website:
    Type: "AWS::CloudFormation::Stack"
    Condition: IsProduction
    Properties:
      TemplateURL: "./website.yml"
      Parameters:
        NamePrefix: !Sub ${ProjectName}-${Environment}
        UserPoolId:
          Fn::GetAtt:
            - CognitoPool
            - Outputs.UserPoolId
        UserPoolClientId:
          Fn::GetAtt:
            - CognitoPool
            - Outputs.UserPoolClientId
        GraphQLApiEndpoint:
          Fn::GetAtt:
            - AppsyncAPI
            - Outputs.GraphQLApiEndpoint
        ApiKey:
          Fn::GetAtt:
            - AppsyncAPI
            - Outputs.ApiKey

Outputs:
  WebsiteDomain:
    Description: The API ID of the GraphQL API
    Value:
      Fn::GetAtt:
        - Website
        - Outputs.Domain
  CognitoUserPoolId:
    Description: The pool id of the cognito user pool
    Value:
      Fn::GetAtt:
        - CognitoPool
        - Outputs.UserPoolId
  CognitoUserPoolClientId:
    Description: The Client ID for AWS AppSync Auth
    Value:
      Fn::GetAtt:
        - CognitoPool
        - Outputs.UserPoolClientId
  QuestionnairesTable:
    Description: The name of the DynamoDB Table
    Value:
      Fn::GetAtt:
        - DynamoDbTable
        - Outputs.QuestionnaireTableID
  GraphQLApiEndpoint:
    Description: The URL to the GraphQL Endpoint
    Value:
      Fn::GetAtt:
        - AppsyncAPI
        - Outputs.GraphQLApiEndpoint
  GraphQLApiKey:
    Description: The API key to the public GraphQL Endpoint
    Value:
      Fn::GetAtt:
        - AppsyncAPI
        - Outputs.ApiKey
  GraphQLApiId:
    Description: The API ID of the GraphQL API
    Value:
      Fn::GetAtt:
        - AppsyncAPI
        - Outputs.GraphQLApiId
